version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - PORT=8000
    volumes:
      - ./:/app
    command: ["gunicorn", "-b", "0.0.0.0:8000", "app:app", "--workers", "3", "--timeout", "120"]

